version: '3'
services:
    mongodb:
        image: 'mongo'
        networks:
            - backup
        environment:
            - MONGO_INITDB_ROOT_USERNAME=backup
            - MONGO_INITDB_ROOT_PASSWORD=backup123
        volumes:
            - .data/mongo:/data/db
        ports:
            - '27017-27019:27017-27019'

    redis:
        image: 'bitnami/redis:latest'
        networks:
            - backup
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
        volumes:
          - .data/redis:/bitnami'

    zookeeper:
        image: 'bitnami/zookeeper:latest'
        networks:
            - backup
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: 'bitnami/kafka:2.8.1-debian-11-r4'
        networks:
            - backup
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
            - ALLOW_PLAINTEXT_LISTENER=yes

    barnabas:
        image: sombreroron/barnabas
        networks:
            - backup
        ports:
            - '39092:39092'
        environment:
            PORT: 39092
            BROKERS: 'kafka:29092'
            TOPICS: Backup
            SSL: 'false'
        depends_on:
            - kafka

networks:
    backup:

